name: Set Up Project

runs:
  using: 'composite'
  steps:
    - name: 'Install PNPM'
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
      with:
        version: 10.34.5 # Optional: Specify the desired pnpm version
        # run_install: true # Optional: Automatically run `pnpm install` after setup

    - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
      uses: nrwl/nx-set-shas@826660b82addbef3abff5fa871492ebad618c9e1 # v4

    - name: 'Setup Node'
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: 'Cache dependencies'
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install
