name: '🧪 CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: 'Set up project'
        uses: ./.github/actions/setup-project

      - name: 'Format Check'
        run: pnpm run nx affected --target=format:check --parallel --max-parallel=2

      - name: 'Lint'
        run: pnpm run nx affected --target=lint --parallel --max-parallel=2

      - name: 'Build'
        run: pnpm run nx affected --target=build --parallel --max-parallel=2
